### ISSUE TITLE
specified example with web3.py [APE-1369]

### ISSUE THREAD

**Issue by JeffXu1** [ApeWorX/eip712#38]
I try to use this library to work with web3.py, I just copy your quick usage exmple as follows:

```py
from eip712.messages import EIP712Message, EIP712Type
from web3 import Web3, Account

class Person(EIP712Type):
    # name: ""
    wallet: "0x8e12f01dae5fe7f1122dc42f2cb084f2f9e8aa03"


class Mail(EIP712Message):
    _chainId_ = 1
    _name_ = "Ether Mail"
    _verifyingContract_ = "0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC"
    _version_ = "1"

    sender: Person
    receiver: Person

if __name__ == '__main__':
    signable_message = Mail.signable_message
    print("signable_message:", signable_message)
    private_key = ''
    account = Account.from_key(private_key)
    signed_message = account.sign_message(signable_message)
    print("singed message is:", signed_message.signature.hex())
```

Then I get the following result:
```py
signable_message: <property object at 0x000001E406348090>
Traceback (most recent call last):
  File "D:\PYE\Crypto\functions\address_interact_func\test3.py", line 24, in <module>
    signed_message = account.sign_message(signable_message)
  File "C:\Users\Lenovo\PycharmProjects\refercode_v3\venv\lib\site-packages\eth_account\signers\local.py", line 83, in sign_message
    return self._publicapi.sign_message(signable_message, private_key=self.key)
  File "C:\Users\Lenovo\PycharmProjects\refercode_v3\venv\lib\site-packages\eth_utils\decorators.py", line 20, in _wrapper
    return self.method(objtype, *args, **kwargs)
  File "C:\Users\Lenovo\PycharmProjects\refercode_v3\venv\lib\site-packages\eth_account\account.py", line 580, in sign_message
    message_hash = _hash_eip191_message(signable_message)
  File "C:\Users\Lenovo\PycharmProjects\refercode_v3\venv\lib\site-packages\eth_account\messages.py", line 66, in _hash_eip191_message
    version = signable_message.version
AttributeError: 'property' object has no attribute 'version'
```

Could you help provide one example with web3.py to use your libray? Thanks!

**Comment by fubuloubu** [comment]
You need to initialize your model:

```py
msg = Mail(receiver, sender)
acct.sign_message(msg signable_message)
...
```
